In [1]:
import torch
import math
import numpy as np
import time

In [2]:
device = ("mps")

In [3]:
tensor1 = torch.randint(0, 500, (100,), device="cpu")
numpyarray = tensor1.cpu().numpy()
print(numpyarray)
print(tensor1)

[171  69 455 232  41 390 108  19   6 110 339  55 211  65 275  65 211 404
   2 246  28 112 146 207  56 480 175  84 417 296 317  72 368 346  74 430
 281 213 302 474 203 414 477  74 401 299  96 343 249  83 176 408 347  28
 361 141 231 104 328 462 394  25 409 211 349 425  49 326 470  92 220  10
 106 405 380 433 417 482 473 314   3 136  10 414 202  63 301 226  48  44
 108 407 345 210 134  72 141  54  30 307]
tensor([171,  69, 455, 232,  41, 390, 108,  19,   6, 110, 339,  55, 211,  65,
        275,  65, 211, 404,   2, 246,  28, 112, 146, 207,  56, 480, 175,  84,
        417, 296, 317,  72, 368, 346,  74, 430, 281, 213, 302, 474, 203, 414,
        477,  74, 401, 299,  96, 343, 249,  83, 176, 408, 347,  28, 361, 141,
        231, 104, 328, 462, 394,  25, 409, 211, 349, 425,  49, 326, 470,  92,
        220,  10, 106, 405, 380, 433, 417, 482, 473, 314,   3, 136,  10, 414,
        202,  63, 301, 226,  48,  44, 108, 407, 345, 210, 134,  72, 141,  54,
         30, 307])


In [13]:
start = time.time()
tensor3 = tensor1.to(device)
end = time.time()
print(end-start)
print(tensor3)

0.0010671615600585938
tensor([171,  69, 455, 232,  41, 390, 108,  19,   6, 110, 339,  55, 211,  65,
        275,  65, 211, 404,   2, 246,  28, 112, 146, 207,  56, 480, 175,  84,
        417, 296, 317,  72, 368, 346,  74, 430, 281, 213, 302, 474, 203, 414,
        477,  74, 401, 299,  96, 343, 249,  83, 176, 408, 347,  28, 361, 141,
        231, 104, 328, 462, 394,  25, 409, 211, 349, 425,  49, 326, 470,  92,
        220,  10, 106, 405, 380, 433, 417, 482, 473, 314,   3, 136,  10, 414,
        202,  63, 301, 226,  48,  44, 108, 407, 345, 210, 134,  72, 141,  54,
         30, 307], device='mps:0')


In [14]:
start = time.time()
tensor3.copy_(tensor1)
end = time.time()
print(end-start)
print(tensor3)

0.000982046127319336
tensor([171,  69, 455, 232,  41, 390, 108,  19,   6, 110, 339,  55, 211,  65,
        275,  65, 211, 404,   2, 246,  28, 112, 146, 207,  56, 480, 175,  84,
        417, 296, 317,  72, 368, 346,  74, 430, 281, 213, 302, 474, 203, 414,
        477,  74, 401, 299,  96, 343, 249,  83, 176, 408, 347,  28, 361, 141,
        231, 104, 328, 462, 394,  25, 409, 211, 349, 425,  49, 326, 470,  92,
        220,  10, 106, 405, 380, 433, 417, 482, 473, 314,   3, 136,  10, 414,
        202,  63, 301, 226,  48,  44, 108, 407, 345, 210, 134,  72, 141,  54,
         30, 307], device='mps:0')


In [15]:
print(tensor1)

tensor([171,  69, 455, 232,  41, 390, 108,  19,   6, 110, 339,  55, 211,  65,
        275,  65, 211, 404,   2, 246,  28, 112, 146, 207,  56, 480, 175,  84,
        417, 296, 317,  72, 368, 346,  74, 430, 281, 213, 302, 474, 203, 414,
        477,  74, 401, 299,  96, 343, 249,  83, 176, 408, 347,  28, 361, 141,
        231, 104, 328, 462, 394,  25, 409, 211, 349, 425,  49, 326, 470,  92,
        220,  10, 106, 405, 380, 433, 417, 482, 473, 314,   3, 136,  10, 414,
        202,  63, 301, 226,  48,  44, 108, 407, 345, 210, 134,  72, 141,  54,
         30, 307])
