In [1]:
import torch
import math

In [2]:
device = ("mps")

In [3]:
tensor1 = torch.tensor([6, 7, 2, 7, 8], dtype=int, device=device)
print(tensor1)
tensor2 = torch.tensor([6, 2, 6], dtype=int, device=device)
print(tensor2)

tensor([6, 7, 2, 7, 8], device='mps:0')
tensor([6, 2, 6], device='mps:0')


In [ ]:
def testFunc(tensor: torch.tensor):
    tensor.add_(5)

In [ ]:
print(tensor1)
testFunc(tensor1)
print(tensor1)

In [5]:
tensor3 = torch.tensor([[6, 1, 8, 2], [2, 7, 8, 3]], dtype=int, device=device)
tensor3

tensor([[6, 1, 8, 2],
        [2, 7, 8, 3]], device='mps:0')

In [7]:
print(torch.sum(tensor3, 1))

tensor([17, 20], device='mps:0')
