In [1]:
import torch
import math
import numpy as np
import time

In [2]:
device = ("mps")

In [3]:
tensor1 = torch.tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8], dtype=int, device=device)
numpyarray = tensor1.cpu().numpy()
tensor2 = torch.tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8], dtype=int, device="cpu")
print(numpyarray)
print(tensor1)
print(tensor2)

[6 7 2 7 8 6 7 2 7 8 6 7 2 7 8 6 7 2 7 8]
tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8],
       device='mps:0')
tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8])


In [ ]:
print(tensor2)
start = time.time()
tempTensor = tensor2.to(device)
start2 = time.time()
tempTensor.add_(1)
end2 = time.time()
print(end2-start2)
tensor2 = tempTensor.to("cpu")
end = time.time()
print(end-start)
print(tensor2)


In [4]:
tensor1

tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8],
       device='mps:0')

In [5]:
tensor3 = tensor1.to("cpu")
print(tensor1)
print(tensor3)

tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8],
       device='mps:0')
tensor([6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8, 6, 7, 2, 7, 8])
